### ISSUE TITLE
Реализовать запросы

### ISSUE THREAD

**Issue by xalvaine** [tasks-xlva/frontend#71]
### Files
- [x] POST `/files`

### Groups
- [x] GET `/groups`
- [x] POST `/groups`
- [x] GET `/groups/:id`
- [x] PATCH `/groups/:id`
- [x] POST `/groups/join`
- [x] GET `/groups/:id/memberships`
- [x] POST `/groups/:id/memberships`
- [x] PATCH `/groups/:id/memberships/:id`
- [x] DELETE `/groups/:id/memberships/:id`

### Subjects
- [x] GET `/subjects`
- [x] POST `/subjects`
- [x] GET `/subjects/:id`
- [x] PATCH `/subjects/:id`
- [x] DELETE `/subjects/:id`

### Tasks
- [x] GET `/tasks`
- [x] POST `/tasks`
- [x] GET `/tasks/:id`
- [x] PATCH `/tasks/:id`
- [x] DELETE `/tasks/:id`

### Token
- [x] POST `/token`
- [x] POST `/token/refresh`

### Users
- [x] POST `/users/`
- [x] GET `/users/me/`
- [x] PATCH `/users/me/`
- [x] POST `/users/activation/`
- [x] POST `/users/reset_password/`
- [x] POST `/users/reset_password_confirm/`
- [x] POST `/users/set_password/`
